version: '3.1'
services:
  web:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./etc/odoo:/etc/odoo/
      #  - ./log:/var/log/odoo
      - ./addons:/mnt/addons
        # - ./python:/mnt/python
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
